# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: codenames.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0f\x63odenames.proto\x12\x0b\x63ode_talker\";\n\nPlayerType\x12\x0c\n\x04team\x18\x01 \x01(\x05\x12\x1f\n\x04role\x18\x02 \x01(\x0e\x32\x11.code_talker.Role\"\x1d\n\x08\x41gentSet\x12\x11\n\tcodenames\x18\x01 \x03(\t\"\x9f\x01\n\x11SecretInformation\x12\x41\n\nagent_sets\x18\x01 \x03(\x0b\x32-.code_talker.SecretInformation.AgentSetsEntry\x1aG\n\x0e\x41gentSetsEntry\x12\x0b\n\x03key\x18\x01 \x01(\x05\x12$\n\x05value\x18\x02 \x01(\x0b\x32\x15.code_talker.AgentSet:\x02\x38\x01\"\xcc\x02\n\x11\x43ommonInformation\x12K\n\x0fidentity_counts\x18\x01 \x03(\x0b\x32\x32.code_talker.CommonInformation.IdentityCountsEntry\x12\x41\n\nagent_sets\x18\x02 \x03(\x0b\x32-.code_talker.CommonInformation.AgentSetsEntry\x12\'\n\x0cturn_history\x18\x03 \x03(\x0b\x32\x11.code_talker.Turn\x1a\x35\n\x13IdentityCountsEntry\x12\x0b\n\x03key\x18\x01 \x01(\x05\x12\r\n\x05value\x18\x02 \x01(\x05:\x02\x38\x01\x1aG\n\x0e\x41gentSetsEntry\x12\x0b\n\x03key\x18\x01 \x01(\x05\x12$\n\x05value\x18\x02 \x01(\x0b\x32\x15.code_talker.AgentSet:\x02\x38\x01\"&\n\x04\x43lue\x12\x0c\n\x04word\x18\x01 \x01(\t\x12\x10\n\x08quantity\x18\x02 \x01(\x05\";\n\nSharedClue\x12\x0c\n\x04team\x18\x01 \x01(\x05\x12\x1f\n\x04\x63lue\x18\x02 \x01(\x0b\x32\x11.code_talker.Clue\"\x17\n\x06\x41\x63tion\x12\r\n\x05guess\x18\x01 \x01(\t\"!\n\rActionOutcome\x12\x10\n\x08identity\x18\x01 \x01(\x05\"u\n\x0cSharedAction\x12\x0c\n\x04team\x18\x01 \x01(\x05\x12#\n\x06\x61\x63tion\x18\x02 \x01(\x0b\x32\x13.code_talker.Action\x12\x32\n\x0e\x61\x63tion_outcome\x18\x03 \x01(\x0b\x32\x1a.code_talker.ActionOutcome\"Y\n\x04Turn\x12%\n\x04\x63lue\x18\x01 \x01(\x0b\x32\x17.code_talker.SharedClue\x12*\n\x07\x61\x63tions\x18\x02 \x03(\x0b\x32\x19.code_talker.SharedAction*9\n\x04Role\x12\x14\n\x10UNSPECIFIED_ROLE\x10\x00\x12\x0e\n\nCLUE_GIVER\x10\x01\x12\x0b\n\x07GUESSER\x10\x02\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'codenames_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _SECRETINFORMATION_AGENTSETSENTRY._options = None
  _SECRETINFORMATION_AGENTSETSENTRY._serialized_options = b'8\001'
  _COMMONINFORMATION_IDENTITYCOUNTSENTRY._options = None
  _COMMONINFORMATION_IDENTITYCOUNTSENTRY._serialized_options = b'8\001'
  _COMMONINFORMATION_AGENTSETSENTRY._options = None
  _COMMONINFORMATION_AGENTSETSENTRY._serialized_options = b'8\001'
  _globals['_ROLE']._serialized_start=992
  _globals['_ROLE']._serialized_end=1049
  _globals['_PLAYERTYPE']._serialized_start=32
  _globals['_PLAYERTYPE']._serialized_end=91
  _globals['_AGENTSET']._serialized_start=93
  _globals['_AGENTSET']._serialized_end=122
  _globals['_SECRETINFORMATION']._serialized_start=125
  _globals['_SECRETINFORMATION']._serialized_end=284
  _globals['_SECRETINFORMATION_AGENTSETSENTRY']._serialized_start=213
  _globals['_SECRETINFORMATION_AGENTSETSENTRY']._serialized_end=284
  _globals['_COMMONINFORMATION']._serialized_start=287
  _globals['_COMMONINFORMATION']._serialized_end=619
  _globals['_COMMONINFORMATION_IDENTITYCOUNTSENTRY']._serialized_start=493
  _globals['_COMMONINFORMATION_IDENTITYCOUNTSENTRY']._serialized_end=546
  _globals['_COMMONINFORMATION_AGENTSETSENTRY']._serialized_start=213
  _globals['_COMMONINFORMATION_AGENTSETSENTRY']._serialized_end=284
  _globals['_CLUE']._serialized_start=621
  _globals['_CLUE']._serialized_end=659
  _globals['_SHAREDCLUE']._serialized_start=661
  _globals['_SHAREDCLUE']._serialized_end=720
  _globals['_ACTION']._serialized_start=722
  _globals['_ACTION']._serialized_end=745
  _globals['_ACTIONOUTCOME']._serialized_start=747
  _globals['_ACTIONOUTCOME']._serialized_end=780
  _globals['_SHAREDACTION']._serialized_start=782
  _globals['_SHAREDACTION']._serialized_end=899
  _globals['_TURN']._serialized_start=901
  _globals['_TURN']._serialized_end=990
# @@protoc_insertion_point(module_scope)
