# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: codenames.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import enum_type_wrapper
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0f\x63odenames.proto\x12\x0b\x63ode_talker\";\n\nPlayerType\x12\x0c\n\x04team\x18\x01 \x01(\x05\x12\x1f\n\x04role\x18\x02 \x01(\x0e\x32\x11.code_talker.Role\"\x1d\n\x08\x41gentSet\x12\x11\n\tcodenames\x18\x01 \x03(\t\"\x9f\x01\n\x11SecretInformation\x12\x41\n\nagent_sets\x18\x01 \x03(\x0b\x32-.code_talker.SecretInformation.AgentSetsEntry\x1aG\n\x0e\x41gentSetsEntry\x12\x0b\n\x03key\x18\x01 \x01(\x05\x12$\n\x05value\x18\x02 \x01(\x0b\x32\x15.code_talker.AgentSet:\x02\x38\x01\"\xcc\x02\n\x11\x43ommonInformation\x12K\n\x0fidentity_counts\x18\x01 \x03(\x0b\x32\x32.code_talker.CommonInformation.IdentityCountsEntry\x12\x41\n\nagent_sets\x18\x02 \x03(\x0b\x32-.code_talker.CommonInformation.AgentSetsEntry\x12\'\n\x0cturn_history\x18\x03 \x03(\x0b\x32\x11.code_talker.Turn\x1a\x35\n\x13IdentityCountsEntry\x12\x0b\n\x03key\x18\x01 \x01(\x05\x12\r\n\x05value\x18\x02 \x01(\x05:\x02\x38\x01\x1aG\n\x0e\x41gentSetsEntry\x12\x0b\n\x03key\x18\x01 \x01(\x05\x12$\n\x05value\x18\x02 \x01(\x0b\x32\x15.code_talker.AgentSet:\x02\x38\x01\"&\n\x04\x43lue\x12\x0c\n\x04word\x18\x01 \x01(\t\x12\x10\n\x08quantity\x18\x02 \x01(\x05\";\n\nSharedClue\x12\x0c\n\x04team\x18\x01 \x01(\x05\x12\x1f\n\x04\x63lue\x18\x02 \x01(\x0b\x32\x11.code_talker.Clue\"\x17\n\x06\x41\x63tion\x12\r\n\x05guess\x18\x01 \x01(\t\"!\n\rActionOutcome\x12\x10\n\x08identity\x18\x01 \x01(\x05\"u\n\x0cSharedAction\x12\x0c\n\x04team\x18\x01 \x01(\x05\x12#\n\x06\x61\x63tion\x18\x02 \x01(\x0b\x32\x13.code_talker.Action\x12\x32\n\x0e\x61\x63tion_outcome\x18\x03 \x01(\x0b\x32\x1a.code_talker.ActionOutcome\"Y\n\x04Turn\x12%\n\x04\x63lue\x18\x01 \x01(\x0b\x32\x17.code_talker.SharedClue\x12*\n\x07\x61\x63tions\x18\x02 \x03(\x0b\x32\x19.code_talker.SharedAction*=\n\x04Role\x12\x14\n\x10UNSPECIFIED_ROLE\x10\x00\x12\x0e\n\nCODEMASTER\x10\x01\x12\x0f\n\x0bINTERPRETER\x10\x02\x62\x06proto3')

_ROLE = DESCRIPTOR.enum_types_by_name['Role']
Role = enum_type_wrapper.EnumTypeWrapper(_ROLE)
UNSPECIFIED_ROLE = 0
CODEMASTER = 1
INTERPRETER = 2


_PLAYERTYPE = DESCRIPTOR.message_types_by_name['PlayerType']
_AGENTSET = DESCRIPTOR.message_types_by_name['AgentSet']
_SECRETINFORMATION = DESCRIPTOR.message_types_by_name['SecretInformation']
_SECRETINFORMATION_AGENTSETSENTRY = _SECRETINFORMATION.nested_types_by_name['AgentSetsEntry']
_COMMONINFORMATION = DESCRIPTOR.message_types_by_name['CommonInformation']
_COMMONINFORMATION_IDENTITYCOUNTSENTRY = _COMMONINFORMATION.nested_types_by_name['IdentityCountsEntry']
_COMMONINFORMATION_AGENTSETSENTRY = _COMMONINFORMATION.nested_types_by_name['AgentSetsEntry']
_CLUE = DESCRIPTOR.message_types_by_name['Clue']
_SHAREDCLUE = DESCRIPTOR.message_types_by_name['SharedClue']
_ACTION = DESCRIPTOR.message_types_by_name['Action']
_ACTIONOUTCOME = DESCRIPTOR.message_types_by_name['ActionOutcome']
_SHAREDACTION = DESCRIPTOR.message_types_by_name['SharedAction']
_TURN = DESCRIPTOR.message_types_by_name['Turn']
PlayerType = _reflection.GeneratedProtocolMessageType('PlayerType', (_message.Message,), {
  'DESCRIPTOR' : _PLAYERTYPE,
  '__module__' : 'codenames_pb2'
  # @@protoc_insertion_point(class_scope:code_talker.PlayerType)
  })
_sym_db.RegisterMessage(PlayerType)

AgentSet = _reflection.GeneratedProtocolMessageType('AgentSet', (_message.Message,), {
  'DESCRIPTOR' : _AGENTSET,
  '__module__' : 'codenames_pb2'
  # @@protoc_insertion_point(class_scope:code_talker.AgentSet)
  })
_sym_db.RegisterMessage(AgentSet)

SecretInformation = _reflection.GeneratedProtocolMessageType('SecretInformation', (_message.Message,), {

  'AgentSetsEntry' : _reflection.GeneratedProtocolMessageType('AgentSetsEntry', (_message.Message,), {
    'DESCRIPTOR' : _SECRETINFORMATION_AGENTSETSENTRY,
    '__module__' : 'codenames_pb2'
    # @@protoc_insertion_point(class_scope:code_talker.SecretInformation.AgentSetsEntry)
    })
  ,
  'DESCRIPTOR' : _SECRETINFORMATION,
  '__module__' : 'codenames_pb2'
  # @@protoc_insertion_point(class_scope:code_talker.SecretInformation)
  })
_sym_db.RegisterMessage(SecretInformation)
_sym_db.RegisterMessage(SecretInformation.AgentSetsEntry)

CommonInformation = _reflection.GeneratedProtocolMessageType('CommonInformation', (_message.Message,), {

  'IdentityCountsEntry' : _reflection.GeneratedProtocolMessageType('IdentityCountsEntry', (_message.Message,), {
    'DESCRIPTOR' : _COMMONINFORMATION_IDENTITYCOUNTSENTRY,
    '__module__' : 'codenames_pb2'
    # @@protoc_insertion_point(class_scope:code_talker.CommonInformation.IdentityCountsEntry)
    })
  ,

  'AgentSetsEntry' : _reflection.GeneratedProtocolMessageType('AgentSetsEntry', (_message.Message,), {
    'DESCRIPTOR' : _COMMONINFORMATION_AGENTSETSENTRY,
    '__module__' : 'codenames_pb2'
    # @@protoc_insertion_point(class_scope:code_talker.CommonInformation.AgentSetsEntry)
    })
  ,
  'DESCRIPTOR' : _COMMONINFORMATION,
  '__module__' : 'codenames_pb2'
  # @@protoc_insertion_point(class_scope:code_talker.CommonInformation)
  })
_sym_db.RegisterMessage(CommonInformation)
_sym_db.RegisterMessage(CommonInformation.IdentityCountsEntry)
_sym_db.RegisterMessage(CommonInformation.AgentSetsEntry)

Clue = _reflection.GeneratedProtocolMessageType('Clue', (_message.Message,), {
  'DESCRIPTOR' : _CLUE,
  '__module__' : 'codenames_pb2'
  # @@protoc_insertion_point(class_scope:code_talker.Clue)
  })
_sym_db.RegisterMessage(Clue)

SharedClue = _reflection.GeneratedProtocolMessageType('SharedClue', (_message.Message,), {
  'DESCRIPTOR' : _SHAREDCLUE,
  '__module__' : 'codenames_pb2'
  # @@protoc_insertion_point(class_scope:code_talker.SharedClue)
  })
_sym_db.RegisterMessage(SharedClue)

Action = _reflection.GeneratedProtocolMessageType('Action', (_message.Message,), {
  'DESCRIPTOR' : _ACTION,
  '__module__' : 'codenames_pb2'
  # @@protoc_insertion_point(class_scope:code_talker.Action)
  })
_sym_db.RegisterMessage(Action)

ActionOutcome = _reflection.GeneratedProtocolMessageType('ActionOutcome', (_message.Message,), {
  'DESCRIPTOR' : _ACTIONOUTCOME,
  '__module__' : 'codenames_pb2'
  # @@protoc_insertion_point(class_scope:code_talker.ActionOutcome)
  })
_sym_db.RegisterMessage(ActionOutcome)

SharedAction = _reflection.GeneratedProtocolMessageType('SharedAction', (_message.Message,), {
  'DESCRIPTOR' : _SHAREDACTION,
  '__module__' : 'codenames_pb2'
  # @@protoc_insertion_point(class_scope:code_talker.SharedAction)
  })
_sym_db.RegisterMessage(SharedAction)

Turn = _reflection.GeneratedProtocolMessageType('Turn', (_message.Message,), {
  'DESCRIPTOR' : _TURN,
  '__module__' : 'codenames_pb2'
  # @@protoc_insertion_point(class_scope:code_talker.Turn)
  })
_sym_db.RegisterMessage(Turn)

if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _SECRETINFORMATION_AGENTSETSENTRY._options = None
  _SECRETINFORMATION_AGENTSETSENTRY._serialized_options = b'8\001'
  _COMMONINFORMATION_IDENTITYCOUNTSENTRY._options = None
  _COMMONINFORMATION_IDENTITYCOUNTSENTRY._serialized_options = b'8\001'
  _COMMONINFORMATION_AGENTSETSENTRY._options = None
  _COMMONINFORMATION_AGENTSETSENTRY._serialized_options = b'8\001'
  _ROLE._serialized_start=992
  _ROLE._serialized_end=1053
  _PLAYERTYPE._serialized_start=32
  _PLAYERTYPE._serialized_end=91
  _AGENTSET._serialized_start=93
  _AGENTSET._serialized_end=122
  _SECRETINFORMATION._serialized_start=125
  _SECRETINFORMATION._serialized_end=284
  _SECRETINFORMATION_AGENTSETSENTRY._serialized_start=213
  _SECRETINFORMATION_AGENTSETSENTRY._serialized_end=284
  _COMMONINFORMATION._serialized_start=287
  _COMMONINFORMATION._serialized_end=619
  _COMMONINFORMATION_IDENTITYCOUNTSENTRY._serialized_start=493
  _COMMONINFORMATION_IDENTITYCOUNTSENTRY._serialized_end=546
  _COMMONINFORMATION_AGENTSETSENTRY._serialized_start=213
  _COMMONINFORMATION_AGENTSETSENTRY._serialized_end=284
  _CLUE._serialized_start=621
  _CLUE._serialized_end=659
  _SHAREDCLUE._serialized_start=661
  _SHAREDCLUE._serialized_end=720
  _ACTION._serialized_start=722
  _ACTION._serialized_end=745
  _ACTIONOUTCOME._serialized_start=747
  _ACTIONOUTCOME._serialized_end=780
  _SHAREDACTION._serialized_start=782
  _SHAREDACTION._serialized_end=899
  _TURN._serialized_start=901
  _TURN._serialized_end=990
# @@protoc_insertion_point(module_scope)
